export const CAR_SELECTED = 'CAR_SELECTED';
export const FILTER_SELECTED = 'FILTER_SELECTED';
export const COLORS_SELECTED = 'COLORS_SELECTED';
export const TARIF_SELECTED = 'TARIF_SELECTED';
export const ALL_CARS = 'ALL_CARS';
export const ALL_TARIFS = 'ALL_TARIFS';